"""Commit and push the summaries a run just produced.

WHY THIS EXISTS. summarize_meeting rebuilds a page as soon as it writes the
sidecar -- so the page is correct on disk immediately -- but it does not
commit, and nothing else in the summary path does either. Publication was
therefore a side effect of TRANSCRIPTION: create_subtitles.push_to_git stages
20*/ when a meeting finishes, which happens every few hours, and it swept up
whatever summaries happened to be sitting there. Measured 2026-09-27: 16
summaries and their rebuilt pages waiting on a transcription that had nothing
to do with them. If transcription stalls, they wait indefinitely -- and the
hourly schedule makes that worse, since summaries now accumulate faster than
transcripts complete.

The git mechanics live in utils.git_publish, shared with the transcriber, so
there is one implementation of "stage, commit, push, and verify against the
REMOTE rather than a cached ref". This file only decides what to say and what
to stage.

Usage:
    python publish_summaries.py            # commit + push if anything changed
    python publish_summaries.py --dry-run
"""

import argparse
import subprocess
import sys

import utils

# The only paths a summary run can touch: the sidecar and the page rebuilt
# from it, both inside the transcript directory.
PATHS = ["20*"]


def pending():
    """Summary sidecars and rebuilt pages not yet committed."""
    out = subprocess.run(["git", "status", "--porcelain", "--"] + PATHS,
                         capture_output=True, text=True).stdout.splitlines()
    return [line[3:] for line in out
            if line[3:].endswith((".summary.json", ".html"))]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    changed = pending()
    summaries = [p for p in changed if p.endswith(".summary.json")]
    if not changed:
        print("nothing to publish")
        return 0

    print("publishing %d summaries (%d files in all)"
          % (len(summaries), len(changed)))
    if args.dry_run:
        for p in changed[:10]:
            print("   " + p)
        return 0

    msg = ("add %d meeting summaries\n\nGenerated by summarize_meeting.py and "
           "rendered into the transcript pages." % len(summaries))
    return 0 if utils.git_publish(PATHS, msg) else 1


if __name__ == "__main__":
    sys.exit(main())
