"""Commit and push the summaries a run just produced.

WHY THIS EXISTS. summarize_meeting rebuilds a page as soon as it writes the
sidecar -- so the page is correct on disk immediately -- but it does not
commit, and nothing else in the summary path does either. Publication was
therefore a side effect of TRANSCRIPTION: create_subtitles.push_to_git stages
20*/ when a meeting finishes, which happens every few hours, and it swept up
whatever summaries happened to be sitting there. Measured 2026-09-27: 16
summaries and their rebuilt pages waiting on a transcription that had nothing
to do with them. If transcription stalls, they wait indefinitely.

WHY NOT CALL create_subtitles.push_to_git. Importing it pulls in whisperx and
a 37-second startup for what is three git commands, and it would load the
transcriber's module-level state into a process that has no business holding
it.

CONCURRENCY IS THE REAL CARE HERE. The transcriber pushes from its own
process, so two pushes can collide on .git/index.lock -- observed during
development. git's own lock is the source of truth; this waits for it rather
than removing it, because a lock held by a LIVE process is doing its job. It
also pulls --rebase before pushing, since the transcriber may have pushed
between our commit and our push.

Usage:
    python publish_summaries.py            # commit + push if anything changed
    python publish_summaries.py --dry-run
"""

import argparse
import os
import subprocess
import sys
import time

# The only paths a summary run can touch: the sidecar and the page rebuilt
# from it, both inside the transcript directory.
PATHS = ["20*"]
LOCK_WAIT_SECONDS = 300


def _git(*args, **kw):
    return subprocess.run(["git"] + list(args), capture_output=True, text=True, **kw)


def wait_for_index_lock(timeout=LOCK_WAIT_SECONDS):
    """Block while another git process holds the index. True if it cleared.

    Deliberately does NOT break the lock. Unlike video_data.lock -- which this
    repo owns and which leaked when a process was killed -- .git/index.lock is
    git's, and removing one held by a live committer corrupts the index.
    """
    lock = os.path.join(".git", "index.lock")
    waited = 0
    while os.path.exists(lock):
        if waited >= timeout:
            print("  .git/index.lock still held after %ds; leaving the summaries "
                  "for the next run rather than forcing it" % timeout)
            return False
        time.sleep(2)
        waited += 2
    return True


def pending():
    """Summary sidecars and rebuilt pages not yet committed."""
    out = _git("status", "--porcelain", "--", *PATHS).stdout.splitlines()
    return [l[3:] for l in out if l[3:].endswith((".summary.json", ".html"))]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    changed = pending()
    summaries = [p for p in changed if p.endswith(".summary.json")]
    if not changed:
        print("nothing to publish")
        return 0
    print("publishing %d summaries (%d files in all)" % (len(summaries), len(changed)))
    if args.dry_run:
        for p in changed[:10]:
            print("   " + p)
        return 0

    if not wait_for_index_lock():
        return 0

    for path in PATHS:
        _git("add", "--", path)
    staged = _git("diff", "--cached", "--name-only").stdout.strip()
    if not staged:
        print("nothing staged after add; another process may have committed it")
        return 0

    msg = ("add %d meeting summaries\n\nGenerated by summarize_meeting.py and "
           "rendered into the transcript pages." % len(summaries))
    r = _git("commit", "-m", msg)
    if r.returncode != 0:
        print("commit failed: %s" % (r.stderr or r.stdout)[:200])
        return 1

    # The transcriber may have pushed between our commit and this push.
    _git("pull", "--rebase", "--quiet", "origin", "main")
    r = _git("push", "--quiet", "origin", "main")
    if r.returncode != 0:
        print("push failed: %s" % (r.stderr or r.stdout)[:200])
        return 1

    # VERIFY AGAINST THE REMOTE, not the cached ref. `git rev-list
    # origin/main..main` compares against whatever was last fetched and has
    # reported "0 unpushed" for a commit that never left the machine.
    local = _git("rev-parse", "HEAD").stdout.strip()
    remote = _git("ls-remote", "origin", "main").stdout.split()
    remote = remote[0] if remote else ""
    if local and local == remote:
        print("pushed %s" % local[:9])
        return 0
    print("PUSH DID NOT LAND: local %s, remote %s" % (local[:9], remote[:9]))
    return 1


if __name__ == "__main__":
    sys.exit(main())
